language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: cd milo && python3 test-unit.py && python3 test-integration.py
notifications:
  email: false
